wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669784029.205098
    t:
      1:
      - 1
      - 33
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 33
      - 41
      - 49
      - 51
      - 55
      3:
      - 17
      - 19
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 1.0e-06
use_distractors:
  desc: null
  value: true
wd:
  desc: null
  value: 0.2
