wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669762375.540083
    t:
      1:
      - 1
      - 33
      - 41
      - 49
      - 51
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 5
